version: '3.0'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker-magento2_default
  web:
    build: ./mlpDockerFile
    image: webapp:tag
    links:
      - db
    env_file:
      - env
    volumes:
      - magento_code:/var/www/html
      - ./mlpDockerFile/auferma:/auferma
    environment:
      - VIRTUAL_HOST=local.magento
    networks:
      - docker-magento2_default
  db:
    build: ./mlpDB
    image: mysql:mlp
    volumes:
      - dbData:/var/lib/mysql/data
    env_file:
      - env
    networks:
      - docker-magento2_default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - VIRTUAL_HOST=phpmyadmin.mlp
    networks:
      - docker-magento2_default
volumes:
  dbData:
  magento_code:
networks:
  docker-magento2_default:
    driver: bridge
